DasunsWebApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profiles.urls')),
]

profiles/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views #import this
from django.urls import reverse_lazy

app_name = "profiles"   

urlpatterns = [
    path('', views.main, name='homepage'),
    path('password_reset/', views.password_reset_request, name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="profiles/password/password_reset_done.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('profiles:password_reset_complete'), template_name="profiles/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="profiles/password/password_reset_complete.html"), name='password_reset_complete'),
    path('spreg/', views.spreg, name='servicep'),
    path("logout", views.logout_request, name='logout'),
    path("booking/", views.booking, name='booking'),
    path('serviceprovider/', views.serviceprovider),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('sps/', views.sps),
    path('serviceuser/', views.serviceuser, name="serviceusers"),
    path('update_serviceuser/<str:pk>', views.updateServiceuser, name="update_serviceuser"),
    path('delete_serviceuser/<str:pk>', views.deleteServiceuser, name="delete_serviceuser"),

]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Serviceuser(models.Model):
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    # objects = models.Manager()

    def __str__(self):
        return self.name

class Serviceprovider(models.Model):
    GENDER = (('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'),)
    fullname = models.CharField(max_length=200)
    # owner = models.ForeignKey(
    #     User, related_name='serviceProviders', on_delete=models.CASCADE, null=True)
    phone = models.CharField(max_length=200)
    email = models.EmailField(max_length=200, unique=True)
    nin = models.CharField(max_length=200)
    dob = models.CharField(max_length=200)
    gender = models.CharField(max_length=200, choices=GENDER)
    phyadd = models.CharField(max_length=200)
    yearexp = models.CharField(max_length=200)
    notmidman = models.CharField(max_length=200)
    skillset = models.CharField(max_length=200)
    internet = models.CharField(max_length=200)
    qualification = models.CharField(max_length=200)
    portifolio = models.CharField(max_length=200, blank=True)
    profession = models.CharField(max_length=200)
    ref1name = models.CharField(max_length=200)
    ref1title = models.CharField(max_length=200)
    ref1email = models.EmailField(max_length=200)
    ref1phone = models.CharField(max_length=200)
    ref2name = models.CharField(max_length=200)
    ref2title = models.CharField(max_length=200)
    ref2email = models.EmailField(max_length=200)
    ref2phone = models.CharField(max_length=200)
    service = models.CharField(max_length=200)
    availability = models.CharField(max_length=200)
    starttime = models.CharField(max_length=200)
    endtime = models.CharField(max_length=200)
    pricevisit = models.CharField(max_length=200, blank=True)
    terms = models.CharField(max_length=200)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.fullname

class Booking(models.Model):
    # STATUS = (('Available', 'Available'), ('Booked', 'Booked'),
    #           ('Not available', 'Not available'))
    meetplace = models.CharField(max_length=200)
    meetdate = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    starttime = models.CharField(max_length=200)
    endtime = models.CharField(max_length=200)
    # owner = models.ForeignKey(
    #     User, related_name='booking', on_delete=models.CASCADE, null=True)
    serviceuser = models.ForeignKey(Serviceuser, null=True, on_delete=models.SET_NULL)
    serviceprovider = models.ForeignKey(Serviceprovider, null=True, on_delete=models.SET_NULL)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    # status = models.CharField(max_length=200, null=True, choices=STATUS)

    def __str__(self):
        return self.meetplace

profiles/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import *

class CreateUserForm(UserCreationForm):
	username = forms.CharField(max_length=254,required=True, widget=forms.TextInput(attrs={'placeholder': 'User Name', 'class': 'form-control'}))
	email = forms.EmailField(max_length=254,required=True, widget=forms.TextInput(attrs={'placeholder': 'Email', 'class': 'form-control'}))
	password1 = forms.CharField(max_length=254,required=True, widget=forms.PasswordInput(attrs={'placeholder': 'Create Password', 'class': 'form-control'}))
	password2 = forms.CharField(max_length=254,required=True, widget=forms.PasswordInput(attrs={'placeholder': 'Confrim Password', 'class': 'form-control'}))
	

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")
		
	def save(self, commit=True):
		user = super(CreateUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user


class ServiceuserForm(ModelForm):
    class Meta:
        model = Serviceuser
        fields = '__all__' 



# from django import forms

# class ContactForm(forms.Form):
#     name = forms.CharField(max_length=30)
#     email = forms.EmailField(max_length=254)
#     message = forms.CharField(
#         max_length=2000,
#         widget=forms.Textarea(),
#         help_text='Write here your message!'
#     )
#     source = forms.CharField(       # A hidden input for internal use
#         max_length=50,              # tell from which page the user sent the message
#         widget=forms.HiddenInput()
#     )

#     def clean(self):
#         cleaned_data = super(ContactForm, self).clean()
#         name = cleaned_data.get('name')
#         email = cleaned_data.get('email')
#         message = cleaned_data.get('message')
#         if not name and not email and not message:
#             raise forms.ValidationError('You have to write something!')


# from django import forms
# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User


# # Create your forms here.

# class SignUpForm(UserCreationForm):
# 	email = forms.EmailField(max_length=254,required=True)

# 	class Meta:
# 		model = User
# 		fields = ("username", "email", "password1", "password2")

# 	def save(self, commit=True):
# 		user = super(SignUpForm, self).save(commit=False)
# 		user.email = self.cleaned_data['email']
# 		if commit:
# 			user.save()
# 		return user

profiles/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from .models import Serviceprovider
from .models import Booking
from .models import Serviceuser as ServiceuserModel
from .forms import CreateUserForm, ServiceuserForm
from django.contrib import messages  # import messages
# from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.forms import AuthenticationForm  # add this
from django.contrib.auth import authenticate, login, logout  # add this
from .models import *
from .filters import BookingFilter
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import *
# added imports
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes



# Create your views here.

def main(request):
	registerform = CreateUserForm()
	loginform = AuthenticationForm()
	context = {'registerform':registerform, 'loginform':loginform }


	if request.method == 'POST':
		if 'registerbtn' in request.POST:
			registerform = CreateUserForm(request.POST)
			if registerform.is_valid():
				registerform.save()
				user = registerform.cleaned_data.get('username')
				messages.success(request, 'Account was created for ' + user)
				return redirect('homepage')
			else:
				messages.error(request, "User was not created")
			loginform = AuthenticationForm(data=request.POST)
		elif 'loginbtn' in request.POST:
			loginform = AuthenticationForm(data=request.POST)
			if loginform.is_valid():
				username = loginform.cleaned_data.get('username')
				password = loginform.cleaned_data.get('password')
				user = authenticate(username=username, password=password)
				if user is not None:
					login(request, user)
					# messages.info(request, f"You are now logged in as {username}")
					return redirect('profiles:homepage')
				else:
					messages.error(request, "No user in the system yet")
			else:
				messages.error(request, "Invalid username or password.")
			loginform = AuthenticationForm()
		return render(request = request,
                    template_name = "profiles/main.html")
	return render(request, 'profiles/main.html', context)


def password_reset_request(request):
	if request.method == "POST":
		password_reset_form = PasswordResetForm(request.POST)
		if password_reset_form.is_valid():
			data = password_reset_form.cleaned_data['email']
			associated_users = User.objects.filter(Q(email=data))
			if associated_users.exists():
				for user in associated_users:
					subject = "Password Reset Requested"
					email_template_name = "profiles/password/password_reset_email.txt"
					c = {
					"email":user.email,
					'domain':'127.0.0.1:8000',
					'site_name': 'Website',
					"uid": urlsafe_base64_encode(force_bytes(user.pk)),
					"user": user,
					'token': default_token_generator.make_token(user),
					'protocol': 'http',
					}
					email = render_to_string(email_template_name, c)
					try:
						send_mail(subject, email, 'admin@example.com' , [user.email], fail_silently=False)
					except BadHeaderError:
						return HttpResponse('Invalid header found.')
					# messages.success(request, 'A message with reset password instructions has been sent to your inbox.')
					return redirect ("/password_reset/done/")
					# return redirect ("profiles:homepage")

	password_reset_form = PasswordResetForm()
	return render(request=request, template_name="profiles/password/password_reset.html", context={"password_reset_form":password_reset_form})


def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.") 
	return redirect("profiles:homepage")


def spreg(request):
    return render(request, 'profiles/spreg.html')


def sps(request):
    bookings = Booking.objects.all()

    context = {'bookings':bookings}
    return render(request, 'profiles/sps.html',context )


def serviceprovider(request):
    serviceproviders = ServiceProvider.objects.all()

    context = {'serviceproviders':serviceproviders}
    return render(request, 'profiles/sps.html', context)

def dashboard(request):
    bookings = Booking.objects.all()
    serviceproviders = Serviceprovider.objects.all()
    serviceusers = ServiceuserModel.objects.all()

    context = {'bookings': bookings, 'serviceproviders': serviceproviders, 'serviceusers': serviceusers}
    return render(request, 'profiles/dashboard.html', context)

def booking(request):
    return render(request, template_name='profiles/bookingform.html')

def serviceuserdash(request):
    return render(request, 'profiles/serviceuserdash.html')


def signuplogin(request):
    return render(request, 'profiles/jointsinlogin.html')

def serviceuser(request):

    serviceusers = ServiceuserModel.objects.all()

    form = ServiceuserForm()
    if request.method == 'POST':
        # print('Printing post:', request.POST)
        form = ServiceuserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse ('profiles:dashboard'))

    context = {'form': form, serviceusers: serviceusers}
    return render(request,'profiles/serviceuser.html', context)

def updateServiceuser(request, pk):

    serviceusers = ServiceuserModel.objects.get(id=pk)
    form = ServiceuserForm(instance=serviceusers)

    if request.method == 'POST':
        form = ServiceuserForm(request.POST, instance=serviceusers)
        if form.is_valid():
            form.save()
            return redirect(reverse ('profiles:dashboard'))

    context = {'form': form}
    return render(request, 'profiles/serviceuser.html', context) 

def deleteServiceuser(request, pk):
    serviceusers = ServiceuserModel.objects.get(id=pk)
    if request.method == "POST":
        serviceusers.delete()
        return redirect(reverse ('profiles:dashboard'))
    context = {'item': serviceusers}
    return render(request, 'profiles/deleteServiceuser.html', context) 

 

# def spreg(request):
#     return render(request, 'profiles/spreg.html')
# def dashboard(request):
#     # book = Book.objects.all()
#     return render(request, 'profiles/dashboard.html',{'bookings':bookings})

# def serviceproviders(request):
#     bookings = Book.objects.all()
#     return render(request, 'profiles/sps.html', {'bookings':bookings})


# def dashboard(request):
#     return render(request, 'profiles/dashboard.html')
# def dashboard(request):
#     return render(request, 'profiles/dashboard.html')


# def register_request(request):
# 	if request.method == "POST":
# 		form = SignUpForm(request.POST)
# 		if form.is_valid():
# 			user = form.save()
# 			login(request, user)
# 			messages.success(request, "Registration successful." )
# 			return redirect("profiles:main")
# 		messages.error(request, "Unsuccessful registration. Invalid information.")
# 	form = SignUpForm
# 	return render (request=request, template_name="profiles/main.html", context={"register_form":form})

# def login_request(request):
# 	if request.method == "POST":
# 		form = AuthenticationForm(request, data=request.POST)
# 		if form.is_valid():
# 			username = form.cleaned_data.get('username')
# 			password = form.cleaned_data.get('password')
# 			user = authenticate(username=username, password=password)
# 			if user is not None:
# 				login(request, user)
# 				messages.info(request, f"You are now logged in as {username}.")
# 				return redirect("profiles:homepage")
# 			else:
# 				messages.error(request,"Invalid username or password.")
# 		else:
# 			messages.error(request,"Invalid username or password.")
# 	form = AuthenticationForm()
# 	return render(request=request, template_name="profiles/main.html", context={"login_form":form})




# def main(request):
# 	signup_form = CreateUserForm()
# 	login_form = AuthenticationForm()
# 	context = {'signup_form':signup_form, 'login_form':login_form }


# 	if request.method == 'POST':
# 		signup_form = CreateUserForm(request.POST)
# 		if signup_form.is_valid():
# 			signup_form.save()
# 			user = signup_form.cleaned_data.get('username')
# 			messages.success(request, 'Account was created for ' + user)
# 			# return redirect('homepage')
# 		else:
# 			messages.error(request, "User was not created")
	
	
# 		# if request.method == 'POST':
# 		login_form = AuthenticationForm(data=request.POST)
# 		if login_form.is_valid():
# 				# username = request.POST.get('username')
# 				# password = request.POST.get('password')
# 			username = login_form.cleaned_data.get('username')
# 			password = login_form.cleaned_data.get('password')
# 			user = authenticate(username=username, password=password)
# 			if user is not None:
# 				login(request, user)
# 				messages.info(request, f"You are now logged in as {username}")
# 				return redirect('profiles:homepage')
# 			else:
# 				messages.error(request, "Invalid username or password.")
# 		else:
# 			messages.error(request, "Invalid username or password.")
# 		login_form = AuthenticationForm()
# 		return render(request = request,
#                     template_name = "profiles/main.html")
#                     # context={"login_form":login_form})
# 	return render(request, 'profiles/main.html', context)

profiles/templates/profiles/admindash.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static '/css/bootstrap/css/bootstrap.css' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static '/css/styles.css' %}"
    />
</head>
<body>
    <div>{% include 'profiles/navbar.html' %}</div>
    <h1>Dashboard</h1>
</body>
</html>

profiles/templates/profiles/banner.html
{% load static %}
<div>
    <img src="{% static 'images/Logo.png' %}" alt="logo">
    
</div>

profiles/templates/profiles/bookingform.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title></title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static '/css/bootstrap/css/bootstrap.css' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static '/css/styles2.css' %}"
    />
  </head>
  <body>
  <div>
   <div>{% include 'profiles/navbar.html' %}</div> 
    <div class="main-booking">
      <div class="card" id="booking-card">
        <form class="" action="" method="POST" id="form">
          {% csrf_token %} 
          {% comment %} {% if Serviceprovider is not None %}           {% endcomment %}
          <h4 class="heading3">
            <small style= "color:black", "fontSize: 30px", "fontWeight:
            bold" > Booking </small> {{Serviceprovider.username}} Mark Shanty
          </h4>
          <h6 class="heading3">
            From {{Serviceprovider.phyadd}} Muyenga Kampala UG
          </h6>
          <h6 class="heading3">
            <small> {{Serviceprovider.pricevisit}} 20000UGX per visit</small>
          </h6>
          <br />
          {% comment %} {% endif %} {% endcomment %}
          <div class="form-group row">
            <label for="" class="col-sm-3 col-form-label"
              >Meeting Place:</label
            >
            <div class="col-sm-9">
              <input
                type="text"
                class="form-control"
                id=""
                placeholder="Preffered meeting place"
              />
            </div>
          </div>
          </br>

          <div class="form-group row">
            <label for="" class="col-sm-3 col-form-label"
              >Meeting Date:</label
            >
            <div class="col-sm-9">
              <input
                type="text"
                class="form-control"
                id=""
                placeholder="Schedule your preffered date"
              />
            </div>
          </div>
          </br>

          <div class="form-group row">
            <label for="" class="col-sm-3 col-form-label"
              >Phone No:</label
            >
            <div class="col-sm-9">
              <input
                type="text"
                class="form-control"
                id=""
                placeholder="Enter your phone number"
              />
            </div>
          </div>
          </br>

          <p class="col-sm-3 col-form-label"><b>Meeting Time:</b></p></br>
          <div class="form-row" id="time-stamp">
            <div class="form-group col-md-5" id="left-time">
              <label for="starttime">Start Time:</label>
              <input
                type="time"
                class="form-control"
                name="starttime"
                id="starttime"
                placeholder="Enter Starting time"
              />
            </div>

           
            <div class="form-group col-md-2"></div>
            
            <div class="form-group col-md-5" id="right-time">
              <label for="endtime" >End Time:</label>
              <input
                type="time"
                class="form-control"
                name="endtime"
                id="endtime"
                placeholder="Enter Ending time"
              />
            </div>
          </div>

          <div class="form-row">
            <input type="submit" value="BOOK NOW"  class="signup-btn" id="book-btn"/>
          </div>
        </form>
      </div>
    </div>
    </div>
  </body>
</html>

profiles/templates/profiles/dashboard.html
{% load static %}
<!DOCTYPE html> 
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dashboard</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static '/css/bootstrap/css/bootstrap.css' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static '/css/styles.css' %}"
    />
  </head>
  <body>
    <div>{% include 'profiles/navbar.html' %}</div>
    <br />
    <h1>Dashboard</h1>
    <br />
    <div>
      <div class="">
        <div class="row" style="width: 95%">
          <div class="col-md">
            <div class="card dashcard1" style="width: 100%">
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Total Orders</li>
                <li class="list-group-item">00</li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="card dashcard1" style="width: 100%">
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Delivered</li>
                <li class="list-group-item">00</li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="card dashcard1" style="width: 100%">
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Pending</li>
                <li class="list-group-item">00</li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="card dashcard1" style="width: 100%">
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Cancelled</li>
                <li class="list-group-item">00</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="orders">
      <h3>Last 10 orders</h3>
      <br />
      <table class="table">
        <thead
          class="thead-dark"
          style="color: #fff; background-color: rgb(12, 83, 39)"
        >
          <tr>
            <th scope="col">Client</th>
            <th scope="col">Service</th>
            <th scope="col">Location</th>
            <th scope="col">Date/time</th>
            <th scope="col">Status</th>
            <th scope="col">Provider</th>
            <th scope="col">Update</th>
            <th scope="col">Cancel</th>
          </tr>
        </thead>
        <tbody>
          {% for booking in bookings %}
          <tr>
            <td><strong>{{booking.serviceuser.name}}</strong></td>
            <td>{{booking.serviceprovider.service}}</td>
            <td>{{booking.meetplace}}</td>
            <td>{{booking.meetdate}}, {{booking.starttime}}</td>
            <td>Pending</td>
            <td>{{booking.serviceprovider.fullname}}</td>
            <td><button type="button" class="btn btn-info">Update</button></td>
            <td>
              <button type="button" class="btn btn-danger">Cancel</button>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="dashSP">
      <h3>Service Providers</h3>
      <br />
      <div>
        <button type="button" class="btn btn-primary btn-lg btn-block">
          Create Service Provider
        </button>
      </div>
      <br />
      <div>
        <table class="table">
          <thead
            class="thead-dark"
            style="color: #fff; background-color: rgb(12, 83, 39)"
          >
            <tr>
              <th scope="col">Service Provider</th>
              <th scope="col">Service</th>

              <th scope="col">Update</th>
              <th scope="col">Cancel</th>
            </tr>
          </thead>
          <tbody>
            {% for serviceprovider in serviceproviders %}
            <tr>
              <td>{{serviceprovider.fullname}}</td>
              <td>{{i.serviceprovider.service}}</td>

              <td>
                <button type="button" class="btn btn-info">Update</button>
              </td>
              <td>
                <button type="button" class="btn btn-danger">Cancel</button>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div>
        <h3>Applications</h3>
        <br />

        <table class="table">
          <thead
            class="thead-dark"
            style="color: #fff; background-color: rgb(12, 83, 39)"
          >
            <tr>
              <th scope="col">Applicant</th>
              <th scope="col">Service</th>
              <th scope="col">date</th>
              <th scope="col">Status</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Mark Morty</td>
              <td>Captioning</td>

              <td>02/03/2020</td>
              <td>Pending</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="orders">
    <table class="table">
      <thead
        class="thead-dark"
        style="color: #fff; background-color: rgb(12, 83, 39)"
      >
        <tr>
          <th scope="col">Client</th>
          <th scope="col">Phone</th>
          <th scope="col">Email</th>

          <th scope="col">Update</th>
          <th scope="col">Cancel</th>
        </tr>
      </thead>
      <tbody>
        {% for serviceuser in serviceusers %}
        <tr>
          <td>{{serviceuser.name}}</td>
          <td>{{serviceuser.phone}}</td>
          <td>{{serviceuser.email}}</td>
          <td>
            <a class="btn btn-info" href="{% url 'profiles:update_serviceuser' serviceuser.id %}">Update</a>
          </td>
          <td>
            <a class="btn btn-danger" href="{% url 'profiles:delete_serviceuser' serviceuser.id %}">Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  </body>
</html>

profiles/templates/profiles/deleteServiceuser.html
{% load static %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dasuns</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static '/css/bootstrap/css/bootstrap.css' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static '/css/styles.css' %}"
    />
  </head>
  <body>
    <div class="container delete" >
      <div class="col-md-6 col-md-offset-3">
        <div class="card">
          <div class="card-body">
            <p>Are you sure you want to delete "{{item}}"?</p>
            <form action="{% url 'profiles:delete_serviceuser' item.id %}" method="POST">
                {% csrf_token %}
              <a class="btn btn-info" href="{% url 'profiles:dashboard'%}">Cancel</a>
              <a
                type="submit"
                class="btn btn-danger"
                href="{% url 'profiles:dashboard'%}" 
                >Confirm</a
              >
            </form>
          </div> 
        </div>
      </div>
    </div>
  </body>
</html>

profiles/templates/profiles/home.html
{% extends 'profiles/main.html'%}
{% load static %}

{% block content %}
<div class="container fluid">
<div>
    <div class="jumbotron jumbotron-fluid ">

        <picture >
        <source media="(min-width:800px)" srcset="{% static 'images/banner.jpg' %}">
        <img src="{% static 'images/banner.jpg' %}" alt="Bootstrap 4 jumbotron" class="jumbotron__background">
      </picture>
</div>
<div>
    <div class="container">
        <div class="row">
          <div class="col-3">
            some random stuff
            One of two columns
          </div>
          <div class="col-3">
            One of two columns
          </div>
        <div class="row justify-content-start">
          <div class="col-3">
            One of two columns
          </div>
          <div class="col-3">
            One of two columns
          </div>
        </div>
</div>
</div>

{% endblock content %}

profiles/templates/profiles/navbar.html
{% load static %}

<container>
  <nav class="navbar navbar-expand-lg navbar-light bg-light nav-fill navbar-right">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"
        >
        <img
          src="{% static 'images/Logo.png' %}"
          alt="logo"
          style="height: 50px"
      />
    </a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse offset-3" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Service</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Who we are</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">How It works</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"><button type="button" class="btn btn-secondary">Request Service</button></a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="#"><button type="button" class="btn btn-secondary">Provide Service</button></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</container>

profiles/templates/profiles/serviceprovider.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Service provider</title>
</head>
<body>
    <div>Service provider</div>
</body>
</html>

profiles/templates/profiles/test.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>